version: "3.9"
services:
  frontend:
    build: {context: ./frontend, dockerfile: Dockerfile.dev}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/sql:/docker-entrypoint-initdb.d

volumes:
  pgdata:
